### PR TITLE
Non-Linear zoom (steps)

### PR DESCRIPTION
**Pull request by B-u-z-z-T**
I have written a longer description in my readme, but the short version: less zoom-change in lower zoom-ranges and higher in higher ranges => feels (visually) more linear'ish. So the steps between every scroll/keypress are not to big at low-zoom or to small in high-zoom.
Integrate as you wish, of course - maybe a cleaner integration, than just a function-copy (of HandleZoomInput(...)) - but it did the job. Also, as already stated in my readme - the configuration for the non-linear zoom is not yet available. Easy to setup, but i couldn't decide for a **good** solution.

### CODE REVIEW

**Comment by space-commits** [comment]
This is a significant change and it's not clear what it aims to accomplish, a comparative video would be best

**Comment by B-u-z-z-T** [comment]
Even with the explanation in the readme, in my branched repo?
I now added the zoom-steps to the ATACR example image (linear/default left, non-linear/new right):
ATACR_4
And i aimed for more/better control over my zoom-states, at lower zoom AND at higher zoom. With the fixed zoom-step-size you either zoomed too much with one step in lower zoomstages, or to little in higher zoom-states - which made it hard to get the right zoom in some situations without a smallzoomstep in the configuration, where you'd have to scroll like 20times for the whole range - so i distributed them non-linear.
Also the code changes seem more than they are: cloned the "HandleZoomInput" (now "HandleLinearZoomInput) to "HandleNonLinearZoomInput" and there i only change the current stepnumber (scrolls/keypresses), so it can be easily calculated (back and forth) - the current step-number will always be calculated to the resulting zoom/magnification, which then will be applied. And with this new change to choose from linear or nonlinear => the whole input-part e.g.:
> if (Input.GetKeyDown(Plugin.VariableZoomOut.Value.MainKey) && Plugin.VariableZoomOut.Value.Modifiers.All(Input.GetKey))

was cloned due to the if condition for either linear or nonlinear and according to that calling HandleLinearZoomInput or HandleNonLinearZoomInput. That is basically all - if there is still something not well enough explained we could also chat about it via discord or something - as you prefer. If there is no value to it, in your opinion, i am also fine with that - i mean, i got it as i wanted it and just thought, somebody else might like/prefer it, too ;P

Also i didn't consider my explanation readme and images to be merged as well - i could branch my stuff again, without explanation and create a new pull request (without readme+imgs)

**Comment by space-commits** [comment]
There is already a PR that aims to do the same thing, their implementation has fewer changes, is there a practical difference between the two as far as end result?

**Comment by B-u-z-z-T** [comment]
Oh... What a timing...^^ Did not see that (Thought it's implemented or not - since FOVFix exists quite long, and it never had that feature - didn't even come to my mind, to check for existing PRs... I'm just a github noob)

Yeah, it aims for the same imprpvement. And yes the other PR is much simpler coded, which is really nice. I'd have to try it, but it seems like, i'd again have trouble finding one ideal setting for all scopes.
There the ZoomStep won't just be added again and again, but used as multiplier for the current zoom.
so e.g. if i have PM II 1x-8x i'd choose like ≈1.52x ZoomStep (factor):
1x - 1.52x - 2.31x - 3.51x - 5.34x - 8.11x => ≈ 5 steps
with Vudu 1x-6x:
1x - 1.52x - 2.31x - 3.51x - 5.34x => ≈ 4 steps
and with ATACR 7x-35x:
6.5x - 9.88x - 15.02x - 22.83x - 34.7x => ≈ 4 steps
The numver of necessary zoomsteps (min<->max) vary a little inconsistent, when comparing the scopes.
It'd also often have zoomsteps with only a fraction of a "full step", at the last step (upwards or downwards) and the zoomstages won't always be the same, when coming from max zoom to min zoom and vice versa - but it does the job!
I'd still have to try it, how it feels - maybe it feels even better.

Also with the others PR solution, i have an idea, how i could simplify my approach a bit, so the code won't be that much changed, as of right now. I'll test it on sunday. (still totally fine, if my version will never be merged - it still fits my needs the most and wanted to share, just in case^^)

**Comment by BobbyRenzobbi** [comment]
> ...the zoomstages won't always be the same, when coming from max zoom to min zoom and vice versa - but it does the job!

Hey, I made PR #38 (now #40), and you have a good point about how in my implementation, zoom steps for zooming out would unfortunately be greater than the zoom steps for zooming in, when ideally they'd be the same. I'll try and work out some solution.

**Comment by BobbyRenzobbi** [comment]
>I'll try and work out some solution.

#40 has been updated with the solution, which fortunately ended up being a more efficient implementation than it was originally. Now, the only thing that's changed is the `HandleZoomInput` method itself (as well as the config)

**Comment by B-u-z-z-T** [comment]
> >I'll try and work out some solution.
> 
> #40 has been updated with the solution, which fortunately ended up being a more efficient implementation than it was originally. Now, the only thing that's changed is the `HandleZoomInput` method itself (as well as the config)

Nice, i still have to test it (tomorrow) and compare the feeling and have to take a look, at how it does work now.

**Comment by space-commits** [comment]
Hey guys, with BSG having implemented variable zoom and SPT 3.10 being around the corner I don't think it's worth implementing these changes at this time, if I decide to make changes I will implement #40 as it changes fewer files and lines of code. Either way this will all haver to be scrapped once SPT 3.10 is out

**Pull request closed without merging**
